import '@/app/globals.css'
import Header from '@/components/header'
import Footer from '../components/footer'

export const metadata = {
  title: 'moriyuki hive',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
